using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Xml;

namespace TexWordCompiler.OutputFiles
{
    class Styles
    {
        public Styles(DirectoryInfo doc)
        {
            Dictionary<string, string> namespaces = new Dictionary<string, string>();
            namespaces.Add("r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships");
            namespaces.Add("w", "http://schemas.openxmlformats.org/wordprocessingml/2006/main");

            OutputFile f = new OutputFile(namespaces, new FileInfo(doc.FullName + "\\word\\styles.xml"), "styles", "w");

            Document docDefaults = new Document("w:docDefaults");
            Document rPrDefault=  new Document("w:rPrDefault");
            Document rPr=  new Document("w:rPr");

            Dictionary<string,string> attributes =  new Dictionary<string,string>();
            attributes.Add("w:asciiTheme", "minorHAnsi");
            attributes.Add("w:eastAsiaTheme", "minorHAnsi");
            attributes.Add("w:hAnsiTheme", "minorHAnsi");
            attributes.Add("w:cstheme", "minorBidi");

            rPr.Add(new Document("w:rFonts", attributes));
            rPr.Add(new Document("w:sz", "w:val","22"));
            rPr.Add(new Document("w:szCs", "w:val", "22"));

            attributes =  new Dictionary<string,string>();
            attributes.Add("w:val", "en-GB");
            attributes.Add("w:eastAsia", "en-US");
            attributes.Add("w:bidi", "ar-SA");

            rPr.Add(new Document("w:lang", attributes));

            rPrDefault.Add(rPr);
            docDefaults.Add(rPrDefault);

            Document pPrDefault =  new Document("w:pPrDefault");
            Document pPr = new Document("w:pPr");
            attributes =  new Dictionary<string,string>();
            attributes.Add("w:after", "200");
            attributes.Add("w:line", "276");
            attributes.Add("w:lineRule", "auto");

            pPr.Add(new Document("w:spacing", attributes));

            pPrDefault.Add(pPr);
            docDefaults.Add(pPrDefault);

            f.Add(docDefaults);


            attributes =  new Dictionary<string,string>();

            attributes.Add("w:defLockedState", "0");
            attributes.Add("w:defUIPriority", "99");
            attributes.Add("w:defSemiHidden", "1");
            attributes.Add("w:defUnhideWhenUsed", "1");
            attributes.Add("w:defQFormat", "0");
            attributes.Add("w:count", "267");
	         Document latentStyles = new Document("w:latentStyles", attributes);

latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Normal");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "0");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 2");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 3");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 4");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 5");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 6");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 7");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 8");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "heading 9");
attributes.Add("w:uiPriority", "9");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 1");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 2");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 3");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 4");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 5");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 6");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 7");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 8");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "toc 9");
attributes.Add("w:uiPriority", "39");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "caption");
attributes.Add("w:uiPriority", "35");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Title");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "10");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Default Paragraph Font");
attributes.Add("w:uiPriority", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Subtitle");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "11");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Strong");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "22");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Emphasis");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "20");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Table Grid");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "59");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Placeholder Text");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "No Spacing");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "1");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Revision");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "List Paragraph");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "34");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Quote");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "29");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Intense Quote");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "30");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3 Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid Accent 1");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3 Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid Accent 2");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3 Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid Accent 3");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3 Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid Accent 4");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3 Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid Accent 5");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Shading Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "60");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light List Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "61");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Light Grid Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "62");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 1 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "63");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Shading 2 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "64");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 1 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "65");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium List 2 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "66");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 1 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "67");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 2 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "68");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Medium Grid 3 Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "69");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Dark List Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "70");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Shading Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "71");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful List Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "72");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Colorful Grid Accent 6");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "73");
attributes.Add("w:unhideWhenUsed", "0");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Subtle Emphasis");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "19");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Intense Emphasis");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "21");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Subtle Reference");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "31");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Intense Reference");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "32");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Book Title");
attributes.Add("w:semiHidden", "0");
attributes.Add("w:uiPriority", "33");
attributes.Add("w:unhideWhenUsed", "0");
attributes.Add("w:qFormat", "1");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "Bibliography");
attributes.Add("w:uiPriority", "37");
latentStyles.Add(new Document("w:lsdException", attributes));
attributes=new Dictionary<string, string>();
attributes.Add("w:name", "TOC Heading");
attributes.Add("w:uiPriority", "39");
attributes.Add("w:qFormat", "1");



            f.Add(latentStyles);

            f.Done();
        }
    }
}
